server:
  port: 9000
spring:
  datasource:
    url: ENC(i8AzYvK+ZeByShgqZ6ofKFI2DrpTCUFvpMmwN3Rxf1c0t2gqoN6qxWCw9BJVjBfYHrQzEC//VZllLWoIDkBRo1z3NdX05YyizzUgZ90Aza9Kwcgh4ZIkAA==)
    username: ENC(MhuDk+u05OhlX8A8jdAnKg==)
    password: ENC(+8mXKpWYkCZcloCXC3vUG17jM02MeQ6l8qEznCSsN8Y=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: mysql
    open-in-view: false
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  mail:
    host: ENC(1RRXK7q5WB8ct1rnep/bnaG9RTcygPWd)
    port: 587
    username: ENC(wvIpM3+wdYpP5RCdPoMEsCvU9SMyBD/5F+qMjC8TfIk=)
    password: ENC(tujso/Sgx1TlwJBGYbZf/fo2Mu1P/5BR4MzfaoymgFw=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  data:
    redis:
      port: 6379
      password: ENC(vSsjiDv1X6o6IU7W3jETnLeO90t2RwAD2PZX1UTeIvQ=)
      host: ENC(YdqJJUGkl4qPFVk3Pi0/rYlsxSKYBX9Q)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(SIjUKpPBCYPefqZTYt9fZcnkTJtmRsaFlkTcqKxdYTFeuPngXVpLc7G3pSclS4+A)
            client-secret: ENC(05WkTu0UcIXNVMl0ZlswfSgwXzU6hd7Qdrq1RJDfk83C05zxm1MKffSUGesajoNN)
            scope:
            client-name: Kakao
            redirect-uri: ENC(2eO5eLJVt0x3dmuoVT+J58KAzz98JRBay7nr/0EKUIFme6GAvm9EsKlhB98fY5BvEFQOzx2vsog=)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
logging:
  config: classpath:logback-spring.xml