server:
  port: 9000
spring:
  application:
    name: gachongo
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - redis
      - email
      - jasypt
      - oauth
      - mysql
      - slack
      - pay
      - s3
    active: local