spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      port: 6379
      host: localhost
      password:

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      port: 6379
      password: ENC(vSsjiDv1X6o6IU7W3jETnLeO90t2RwAD2PZX1UTeIvQ=)
      host: ENC(yoG/kVYpR24xGDk2uEakGOQWHvjv1gr9)
